import React, { useMemo, useEffect, useCallback } from "react";
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  useNodesState,
  useEdgesState,
  MarkerType,
} from "@xyflow/react";
import { useTelemetry } from "@/context/TelemetryContext";
import CustomNode from "@/components/CustomNode";
import { getLayoutedElements } from "@/utils/dagreLayout";

const nodeTypes = {
  agentNode: CustomNode,
};

/**
 * TelemetryMap renders the React Flow graph with automatic Dagre layout
 * and dynamic incoming/outgoing edge animations when an agent is selected.
 */
export default function TelemetryMap() {
  const {
    telemetryData,
    selectedAgentId,
    setSelectedAgentId,
    layoutDirection,
    theme,
  } = useTelemetry();

  const [nodes, setNodes, onNodesChange] = useNodesState([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);

  // Compute base nodes and edges from telemetryData
  const { rawNodes, rawEdges } = useMemo(() => {
    if (!telemetryData || !telemetryData.agents) {
      return { rawNodes: [], rawEdges: [] };
    }

    const initialNodes = telemetryData.agents.map((agent) => ({
      id: agent.id,
      type: "agentNode",
      data: { ...agent },
      position: { x: 0, y: 0 },
    }));

    const initialEdges = (telemetryData.flows || []).map((flow, idx) => ({
      id: `edge-${flow.source}-${flow.target}-${idx}`,
      source: flow.source,
      target: flow.target,
      label: flow.label || "",
      type: "smoothstep",
      markerEnd: {
        type: MarkerType.ArrowClosed,
        width: 16,
        height: 16,
      },
    }));

    return { rawNodes: initialNodes, rawEdges: initialEdges };
  }, [telemetryData]);

  // Recalculate auto-layout using dagre when raw data or direction changes
  useEffect(() => {
    if (rawNodes.length === 0) return;

    const { nodes: layoutedNodes, edges: layoutedEdges } = getLayoutedElements(
      rawNodes,
      rawEdges,
      layoutDirection
    );

    setNodes(layoutedNodes);
    setEdges(layoutedEdges);
  }, [rawNodes, rawEdges, layoutDirection, setNodes, setEdges]);

  // Update edges dynamically based on selectedAgentId and theme
  const styledEdges = useMemo(() => {
    const isLight = theme === "light";

    return edges.map((edge) => {
      // If no agent is selected, render default subtle styling
      if (!selectedAgentId) {
        return {
          ...edge,
          animated: false,
          style: {
            stroke: isLight ? "#94a3b8" : "#64748b",
            strokeWidth: 1.5,
            opacity: 0.85,
          },
          labelStyle: {
            fill: isLight ? "#475569" : "#94a3b8",
            fontSize: 11,
            fontWeight: 500,
          },
          labelBgStyle: {
            fill: isLight ? "#ffffff" : "#0f172a",
            fillOpacity: isLight ? 0.95 : 0.85,
            rx: 4,
            ry: 4,
            stroke: isLight ? "#e2e8f0" : "transparent",
            strokeWidth: isLight ? 1 : 0,
          },
          markerEnd: {
            type: MarkerType.ArrowClosed,
            width: 16,
            height: 16,
            color: isLight ? "#94a3b8" : "#64748b",
          },
        };
      }

      const isIncoming = edge.target === selectedAgentId;
      const isOutgoing = edge.source === selectedAgentId;

      if (isIncoming) {
        // Highlighting INCOMING edge (Data arriving to this agent)
        return {
          ...edge,
          animated: true,
          style: {
            stroke: isLight ? "#0284c7" : "#38bdf8", // Sky blue for input flow
            strokeWidth: 3,
            strokeDasharray: "6 3",
            filter: isLight
              ? "drop-shadow(0px 0px 4px rgba(2, 132, 199, 0.4))"
              : "drop-shadow(0px 0px 6px rgba(56, 189, 248, 0.6))",
            zIndex: 10,
          },
          labelStyle: {
            fill: isLight ? "#0369a1" : "#38bdf8",
            fontSize: 12,
            fontWeight: 700,
          },
          labelBgStyle: {
            fill: isLight ? "#f0f9ff" : "#082f49",
            fillOpacity: 0.95,
            rx: 6,
            ry: 6,
            stroke: isLight ? "#0284c7" : "#38bdf8",
            strokeWidth: 1,
          },
          markerEnd: {
            type: MarkerType.ArrowClosed,
            width: 20,
            height: 20,
            color: isLight ? "#0284c7" : "#38bdf8",
          },
        };
      }

      if (isOutgoing) {
        // Highlighting OUTGOING edge (Data generated by this agent)
        return {
          ...edge,
          animated: true,
          style: {
            stroke: isLight ? "#059669" : "#34d399", // Emerald green for output flow
            strokeWidth: 3,
            strokeDasharray: "6 3",
            filter: isLight
              ? "drop-shadow(0px 0px 4px rgba(5, 150, 105, 0.4))"
              : "drop-shadow(0px 0px 6px rgba(52, 211, 153, 0.6))",
            zIndex: 10,
          },
          labelStyle: {
            fill: isLight ? "#047857" : "#34d399",
            fontSize: 12,
            fontWeight: 700,
          },
          labelBgStyle: {
            fill: isLight ? "#ecfdf5" : "#064e3b",
            fillOpacity: 0.95,
            rx: 6,
            ry: 6,
            stroke: isLight ? "#059669" : "#34d399",
            strokeWidth: 1,
          },
          markerEnd: {
            type: MarkerType.ArrowClosed,
            width: 20,
            height: 20,
            color: isLight ? "#059669" : "#34d399",
          },
        };
      }

      // Edge not directly connected to the active agent: dim it down
      return {
        ...edge,
        animated: false,
        style: {
          stroke: isLight ? "#cbd5e1" : "#334155",
          strokeWidth: 1,
          opacity: isLight ? 0.45 : 0.25,
        },
        labelStyle: {
          fill: isLight ? "#94a3b8" : "#475569",
          fontSize: 10,
          opacity: 0.4,
        },
        labelBgStyle: {
          fill: isLight ? "#f8fafc" : "#0f172a",
          fillOpacity: 0.5,
          rx: 4,
          ry: 4,
        },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: isLight ? "#cbd5e1" : "#334155",
        },
      };
    });
  }, [edges, selectedAgentId, theme]);

  // Node click handler
  const handleNodeClick = useCallback(
    (_, node) => {
      setSelectedAgentId(node.id);
    },
    [setSelectedAgentId]
  );

  // Background / Canvas click handler: deselect agent
  const handlePaneClick = useCallback(() => {
    setSelectedAgentId(null);
  }, [setSelectedAgentId]);

  const isLight = theme === "light";

  return (
    <div className="w-full h-full relative">
      <ReactFlow
        nodes={nodes}
        edges={styledEdges}
        nodeTypes={nodeTypes}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onNodeClick={handleNodeClick}
        onPaneClick={handlePaneClick}
        deleteKeyCode={null}
        selectionKeyCode={null}
        multiSelectionKeyCode={null}
        fitView
        fitViewOptions={{ padding: 0.25 }}
        minZoom={0.2}
        maxZoom={1.5}
        defaultEdgeOptions={{ type: "smoothstep" }}
        className={isLight ? "bg-[#f8fafc]" : "bg-[#02040a]"}
      >
        <Background
          variant="dots"
          gap={22}
          size={1.2}
          color={isLight ? "#cbd5e1" : "#1e293b"}
        />
        <Controls
          className={
            isLight
              ? "bg-white border border-slate-200 text-slate-700 shadow-md"
              : "bg-slate-900 border border-slate-700/70 text-slate-300 shadow-xl"
          }
          showInteractive={false}
        />
        <MiniMap
          nodeStrokeColor="#38bdf8"
          nodeColor={isLight ? "#cbd5e1" : "#1e293b"}
          nodeBorderRadius={6}
          maskColor={
            isLight ? "rgba(241, 245, 249, 0.75)" : "rgba(2, 4, 10, 0.85)"
          }
          className={
            isLight
              ? "border border-slate-200 rounded-lg overflow-hidden bg-white/95 !bottom-4 !right-4 shadow-md"
              : "border border-slate-700/70 rounded-lg overflow-hidden bg-slate-900/95 !bottom-4 !right-4 shadow-xl"
          }
          zoomable
          pannable
        />
      </ReactFlow>

      {/* Floating Canvas Legend */}
      <div
        className={
          isLight
            ? "absolute top-4 left-4 z-10 flex items-center gap-3 bg-white/95 backdrop-blur-md px-3.5 py-2 rounded-lg border border-slate-200 text-xs text-slate-700 shadow-md"
            : "absolute top-4 left-4 z-10 flex items-center gap-3 bg-slate-900/95 backdrop-blur-md px-3.5 py-2 rounded-lg border border-slate-700/70 text-xs text-slate-300 shadow-[0_10px_25px_-5px_rgba(0,0,0,0.7),inset_0_1px_0_0_rgba(255,255,255,0.08)]"
        }
      >
        <span
          className={
            isLight ? "font-semibold text-slate-900" : "font-semibold text-slate-200"
          }
        >
          Flow Legend:
        </span>
        <div className="flex items-center gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full bg-sky-400 shadow-[0_0_8px_#38bdf8]" />
          <span>Inbound (Input)</span>
        </div>
        <div className="flex items-center gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]" />
          <span>Outbound (Output)</span>
        </div>
        {selectedAgentId && (
          <button
            onClick={() => setSelectedAgentId(null)}
            className={
              isLight
                ? "ml-2 text-[11px] text-slate-500 hover:text-slate-900 underline cursor-pointer"
                : "ml-2 text-[11px] text-slate-400 hover:text-slate-200 underline cursor-pointer"
            }
          >
            Deselect
          </button>
        )}
      </div>
    </div>
  );
}
